# Generated by Django 5.0.3 on 2024-03-29 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0003_alter_fotografia_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotografia',
            name='categoria',
            field=models.CharField(choices=[('Nebulosa', 'Nebulosa'), ('Estrela', 'Estrela'), ('Galáxia', 'Galaxia'), ('Planeta', 'Planeta'), ('Satélite', 'Satélite')], default='', max_length=100),
        ),
    ]
